-- ============================================================
-- Cortex Database Schema — Week 5
-- SEARCH — pgvector embeddings over events for semantic + keyword search.
--
-- Embeddings are OpenAI text-embedding-3-small (1536 dims), generated by the
-- extraction persist step from the event summary + raw content, and covering
-- transcripts, emails, and OCR'd photo text (all of which live in events).
-- Reverses AD-013's "no embeddings yet" now that search is the Week 5 feature.
-- Apply AFTER 004 in the Supabase SQL Editor.
-- ============================================================
create extension if not exists vector;

alter table public.events
  add column if not exists embedding vector(1536);

-- Approximate-nearest-neighbour index for cosine distance.
create index if not exists idx_events_embedding
  on public.events using ivfflat (embedding vector_cosine_ops)
  with (lists = 100);

-- Semantic match, scoped to the caller via auth.uid() so RLS intent holds even
-- though the function reads the table directly. Call with the RLS-scoped server
-- client (not the service role, whose auth.uid() is null).
create or replace function public.match_events(
  query_embedding vector(1536),
  match_count int default 20,
  similarity_threshold float default 0.2
)
returns table (id uuid, similarity float)
language sql
stable
as $$
  select e.id, 1 - (e.embedding <=> query_embedding) as similarity
  from public.events e
  where e.user_id = auth.uid()
    and e.is_deleted = false
    and e.embedding is not null
    and 1 - (e.embedding <=> query_embedding) > similarity_threshold
  order by e.embedding <=> query_embedding
  limit match_count;
$$;
